### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by Icelagy** [ContionMig/Mitsuzi-JS#1]
C:\Users\daddy\OneDrive\Escritorio\Nicolas Files\Mitsuzi-JS-main>node index.js
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module 'canvas'
Require stack:
- C:\Users\daddy\OneDrive\Escritorio\Nicolas Files\Mitsuzi-JS-main\util\MitUtil.js
- C:\Users\daddy\OneDrive\Escritorio\Nicolas Files\Mitsuzi-JS-main\index.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:687:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:903:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:74:18)[39m
    at Object.<anonymous> (C:\Users\daddy\OneDrive\Escritorio\Nicolas Files\Mitsuzi-JS-main\util\MitUtil.js:1:16)
[90m    at Module._compile (internal/modules/cjs/loader.js:1015:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:879:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:724:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:903:19)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\Users\\daddy\\OneDrive\\Escritorio\\Nicolas Files\\Mitsuzi-JS-main\\util\\MitUtil.js'[39m,
    [32m'C:\\Users\\daddy\\OneDrive\\Escritorio\\Nicolas Files\\Mitsuzi-JS-main\\index.js'[39m
  ]
}

**Comment by ContionMig** [comment]
Please make sure to install all the packages required.

`npm i @discordjs/opus@0.3.2 anime-facts@1.0.7 animefreak@1.0.2 animequotes@1.1.2 asciify-image@0.1.6 bad-words@3.0.3 canvas@2.6.1 common-tags@1.8.0 cpu-stat@2.0.1 crawler@1.2.2 crazy-quotes@1.0.4 crypto-price@0.0.6 dabi-images@2.7.5 dblapi.js@2.4.0 discord-anti-spam@2.4.1 discord.js@12.3.1 ffmpeg@0.0.4 fluent-ffmpeg@2.1.2 genius-api@0.4.1 genius-lyrics-api@3.0.2 giphy-wrapper@0.0.3 insult@0.0.3 level@6.0.1 lyrics-finder@21.0.5 mathjs@7.1.0 minecraft-server-status@1.0.1 moment@2.27.0 morse@0.1.0 newsapi@2.4.1 node-os-utils@1.3.0 node-osu@2.2.0 node-superfetch@0.1.10 one-liner-joke@1.2.0 owofy@1.0.2 pastebin-js@1.0.5 proxy-list-random@1.0.2 quick.db@7.1.1 random-animal-name@0.1.0 random-cat@1.0.1 random-number@0.0.9 random-words@1.1.1 rss-parser@3.9.0 simple-youtube-api@5.2.1 soundcloud-downloader@0.1.3 sqlite3@5.0.0 stackimpact@1.3.26 steamapi@2.1.1 string-similarity@4.0.2 systeminformation@4.27.0 urban-dictionary@2.2.1 url-exists@1.0.3 util@0.12.3 valid-url@1.0.9 weather-js@2.0.0 website-scraper@4.2.2 yo-mamma@1.3.0 ytdl-core@3.2.0 ytdl-core-discord@1.2.1 zlib-sync@0.1.7`

**Comment by Icelagy** [comment]
I will try to use it, and I will text back if it doesnt work

**Comment by Icelagy** [comment]
Do you have discord or something? So you can help or idk?

**Comment by Icelagy** [comment]
There are some things that I don't understand.
