### ISSUE TITLE
Can't run Start.Bat

### ISSUE THREAD

**Issue by AyelLynx** [ContionMig/Mitsuzi-JS#17]
Hello I can't run start.bat even tho I install the packages? can you help me?

**Comment by ContionMig** [comment]
what are the errors? if this is your first time with node.js, i would recommend doing more research on it before running this.

**Comment by AyelLynx** [comment]
C:\Users\USER\Desktop\Mitsuzi-JS-main>node index.js --inspect 
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module '../build/Release/canvas.node'
