### ISSUE TITLE
how do i setup pastebin feature?

### ISSUE THREAD

**Issue by nososho** [ContionMig/Mitsuzi-JS#5]
I was wondering how to setup the pastebin feature, could i please get help? Please reply to me or dm me in discord at "xEncarium#0001" or if that doesnt work try xEncarium#2380, thanks for reading this

**Comment by ContionMig** [comment]
There is already a package for this,
https://www.npmjs.com/package/pastebin-js
https://www.npmjs.com/package/better-pastebin
