### ISSUE TITLE
image letters

### ISSUE THREAD

**Issue by nososho** [ContionMig/Mitsuzi-JS#6]
when i run +typetest, +profile, etc the letters dont appear only small boxes, how do i fix this?

**Comment by ContionMig** [comment]
i am pretty sure its a font issue. just go and see if you are missing a font.

**Comment by minecraftfan424** [comment]
How do I do that?

**Comment by nososho** [comment]
> i am pretty sure its a font issue. just go and see if you are missing a font.

How do I do that?
